backend_latest/mcod/cms/urls.py
from django.conf import settings
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from django.urls import path
from wagtail.core.utils import WAGTAIL_APPEND_SLASH

from mcod.cms import views

if WAGTAIL_APPEND_SLASH:
    serve_pattern = r"^((?:[\w\-]+/)*)$"
else:
    serve_pattern = r"^([\w\-/]*)$"


WAGTAIL_FRONTEND_LOGIN_TEMPLATE = getattr(settings, "WAGTAIL_FRONTEND_LOGIN_TEMPLATE", "wagtailcore/login.html")


urlpatterns = [
    url(
        r"^_util/authenticate_with_password/(\d+)/(\d+)/$",
        views.authenticate_with_password,
        name="wagtailcore_authenticate_with_password",
    ),
    url(
        r"^_util/login/$",
        auth_views.LoginView.as_view(template_name=WAGTAIL_FRONTEND_LOGIN_TEMPLATE),
        name="wagtailcore_login",
    ),
    path("copy_pl_to_en/<int:page_id>/", views.copy_pl_to_en, name="copy_pl_to_en"),
    url(serve_pattern, views.serve, name="wagtail_serve"),
]

form_urls = [
    url(r"^$", views.FormPagesListView.as_view(), name="cms_forms_index"),
    url(
        r"^submissions/(?P<page_id>\d+)/$",
        views.get_submissions_list_view,
        name="cms_forms_list_submissions",
    ),
    url(
        r"^submissions/(?P<page_id>\d+)/delete/$",
        views.DeleteSubmissionsView.as_view(),
        name="cms_forms_delete_submissions",
    ),
]

chooser_urls = [
    url(
        r"^choose-titled-external-link/$",
        views.titled_external_link,
        name="wagtailadmin_choose_page_titled_external_link",
    ),
    url(
        r"^choose-titled-page/$",
        views.titled_browse,
        name="wagtailadmin_choose_titled_page",
    ),
    url(
        r"^choose-titled-page/(\d+)/$",
        views.titled_browse,
        name="wagtailadmin_choose_titled_page_child",
    ),
    url(
        r"^choose-titled-email-link/$",
        views.titled_email_link,
        name="wagtailadmin_choose_page_titled_email_link",
    ),
    url(
        r"^choose-titled-phone-link/$",
        views.titled_phone_link,
        name="wagtailadmin_choose_page_titled_phone_link",
    ),
    url(
        r"^choose-titled-anchor-link/$",
        views.titled_anchor_link,
        name="wagtailadmin_choose_page_titled_anchor_link",
    ),
]

backend_latest/mcod/pn_apps/urls.py
from pathlib import Path

from bokeh.server.django import autoload
from bokeh.server.django.routing import document
from django.conf import settings
from django.urls import path

from mcod.pn_apps import stats_app, views

urlpatterns = [
    path("stats/", views.stats_dashboard, name="stats"),
    path("charts/slot-<int:slot>.png", views.chart_thumbnail),
    path("notebooks/<notebook>", views.short_apps),
]

notebooks_dir = Path(settings.ROOT_DIR + "notebooks")

bokeh_apps = [
    autoload("pn-apps/stats", stats_app.app),
]

for notebook in notebooks_dir.glob("*.ipynb"):
    notebook_path = "pn-apps/" + str(notebook.relative_to(settings.ROOT_DIR))
    bokeh_apps.append(document(notebook_path, notebook))

backend_latest/mcod/urls.py
from bokeh.server.django import static_extensions
from django.apps import apps
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.http import JsonResponse
from django.urls import path, re_path
from django.views.generic.base import TemplateView
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls
from wagtail.documents.api.v2.views import DocumentsAPIViewSet

from mcod.cms import urls as cms_urls
from mcod.cms.api.router import CmsApiRouter
from mcod.cms.api.views import CmsPagesViewSet, ImagesViewSet
from mcod.cms.views import revisions_view
from mcod.core.admin_metrics_view import prometheus_metrics_view
from mcod.datasets.views import ConditionLabelsAdminView, DatasetAutocompleteView
from mcod.organizations.views import InstitutionTypeAdminView, OrganizationAutocompleteView
from mcod.regions.views import RegionsAutocompleteView
from mcod.resources.views import ResourceAutocompleteView
from mcod.users.views import (
    AdminAutocompleteView,
    AgentAutocompleteView,
    CustomAdminLoginView,
    StaffAutocompleteView,
)

panel_app_config = apps.get_app_config("mcod.pn_apps")

urlpatterns = [path("health/", lambda r: JsonResponse({"status": "ok"}))]

if settings.COMPONENT == "cms":
    api_router = CmsApiRouter("cmsapi")
    api_router.register_endpoint("pages", CmsPagesViewSet)
    api_router.register_endpoint("images", ImagesViewSet)
    api_router.register_endpoint("documents", DocumentsAPIViewSet)

    urlpatterns += [
        re_path(r"^documents/", include(wagtaildocs_urls)),
        re_path(r"^api/", api_router.urls),
        re_path(r"^hypereditor/", include("hypereditor.urls")),
        re_path(
            r"^admin/pages/(\d+)/revisions/(\d+)/view/$",
            revisions_view,
            name="revisions_view",
        ),
        re_path(r"^admin/", include(wagtailadmin_urls)),
        re_path(
            r"^robots.txt",
            TemplateView.as_view(template_name="admin/robots.txt", content_type="text/plain"),
        ),
        re_path(r"", include(cms_urls)),
    ]
    urlpatterns += static(settings.IMAGES_URL, document_root=settings.IMAGES_MEDIA_ROOT)
else:
    urlpatterns += [
        path("metrics/", prometheus_metrics_view),
        path("nested_admin/", include("nested_admin.urls")),
        path("ckeditor/", include("ckeditor_uploader.urls")),
        path(
            "organization-type/",
            InstitutionTypeAdminView.as_view(),
            name="organization-type",
        ),
        path(
            "organization-autocomplete/",
            OrganizationAutocompleteView.as_view(),
            name="organization-autocomplete",
        ),
        path(
            "dataset-autocomplete/",
            DatasetAutocompleteView.as_view(),
            name="dataset-autocomplete",
        ),
        path(
            "staff-autocomplete/",
            StaffAutocompleteView.as_view(),
            name="staff-autocomplete",
        ),
        path(
            "admin-autocomplete/",
            AdminAutocompleteView.as_view(),
            name="admin-autocomplete",
        ),
        path(
            "agent-autocomplete/",
            AgentAutocompleteView.as_view(),
            name="agent-autocomplete",
        ),
        path(
            "regions-autocomplete/",
            RegionsAutocompleteView.as_view(),
            name="regions-autocomplete",
        ),
        path(
            "resource-autocomplete/",
            ResourceAutocompleteView.as_view(),
            name="resource-autocomplete",
        ),
        path(
            "dataset-license-labels/",
            ConditionLabelsAdminView.as_view(),
            name="dataset-license-labels",
        ),
        path("i18n/", include("django.conf.urls.i18n")),
        path("login/", CustomAdminLoginView.as_view(), name="login"),
        path("", admin.site.urls, name="admin"),
        # Non-admin urls
        path("pn-apps/", include("mcod.pn_apps.urls")),
        path("discourse/", include("mcod.discourse.urls")),
        path(
            "robots.txt",
            TemplateView.as_view(template_name="admin/robots.txt", content_type="text/plain"),
        ),
    ]
    urlpatterns += staticfiles_urlpatterns()

urlpatterns += static_extensions()
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += [path("logingovpl/", include("mcod.users.urls"))]

backend_latest/mcod/users/urls.py
from django.urls import path

from mcod.users.views import ACSView, LogingovplSwitchView, LogingovplUnlinkView, SSOView

urlpatterns = [
    path("", SSOView.as_view(), name="logingovpl"),
    path("idp", ACSView.as_view(), name="idp"),
    path("unlink", LogingovplUnlinkView.as_view(), name="unlink"),
    path("switch", LogingovplSwitchView.as_view(), name="switch"),
]

backend_latest/mcod/articles/models.py
from django.apps import apps
from django.contrib.auth import get_user_model
from django.contrib.contenttypes.models import ContentType
from django.contrib.postgres.indexes import GinIndex
from django.db import models
from django.utils.translation import gettext_lazy as _
from model_utils import FieldTracker
from modeltrans.fields import TranslationField

from mcod.core.db.managers import TrashManager
from mcod.core.db.models import ExtendedModel, TrashModelBase
from mcod.core.managers import SoftDeletableManager
from mcod.lib.widgets import RichTextUploadingField

User = get_user_model()


CATEGORY_TYPES = (
    ("article", _("Article")),
    ("knowledge_base", _("Knowledge base")),
    ("unlisted", _("Not listed")),
)


class ArticleCategory(ExtendedModel):

    name = models.CharField(max_length=100, unique=True, verbose_name=_("name"))
    type = models.CharField(
        max_length=20,
        choices=CATEGORY_TYPES,
        verbose_name=_("type"),
        default="unlisted",
    )
    description = models.CharField(max_length=500, blank=True, verbose_name=_("Description"))

    created_by = models.ForeignKey(
        User,
        models.DO_NOTHING,
        blank=False,
        editable=False,
        null=True,
        verbose_name=_("Created by"),
        related_name="article_categories_created",
    )
    modified_by = models.ForeignKey(
        User,
        models.DO_NOTHING,
        blank=False,
        editable=False,
        null=True,
        verbose_name=_("Modified by"),
        related_name="article_categories_modified",
    )

    @property
    def image_url(self):
        return ""

    def __str__(self):
        return self.name_i18n

    i18n = TranslationField(fields=("name", "description"), required_languages=("pl",))

    tracker = FieldTracker()
    slugify_field = "name"

    objects = SoftDeletableManager()
    trash = TrashManager()

    class Meta:
        verbose_name = _("Article Category")
        verbose_name_plural = _("Article Categories")
        db_table = "article_category"
        default_manager_name = "objects"
        indexes = [
            GinIndex(fields=["i18n"]),
        ]


class Article(ExtendedModel):

    title = models.CharField(max_length=300, verbose_name=_("Title"))
    notes = RichTextUploadingField(verbose_name=_("Notes"), null=True)
    license_old_id = models.CharField(max_length=20, blank=True, null=True, verbose_name=_("License ID"))
    license = models.ForeignKey(
        "licenses.License",
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True,
        verbose_name=_("License ID"),
    )
    author = models.CharField(max_length=50, blank=True, null=True, verbose_name=_("Author"))
    category = models.ForeignKey(ArticleCategory, on_delete=models.PROTECT, verbose_name=_("Category"))
    tags = models.ManyToManyField(
        "tags.Tag",
        db_table="article_tag",
        blank=True,
        verbose_name=_("Tags"),
        related_name="articles",
        related_query_name="article",
    )
    datasets = models.ManyToManyField(
        "datasets.Dataset",
        db_table="article_dataset",
        verbose_name=_("Datasets"),
        related_name="articles",
        related_query_name="article",
    )

    created_by = models.ForeignKey(
        User,
        models.DO_NOTHING,
        blank=False,
        editable=False,
        null=True,
        verbose_name=_("Created by"),
        related_name="articles_created",
    )
    modified_by = models.ForeignKey(
        User,
        models.DO_NOTHING,
        blank=False,
        editable=False,
        null=True,
        verbose_name=_("Modified by"),
        related_name="articles_modified",
    )

    @classmethod
    def accusative_case(cls):
        return _("acc: Article")

    def __str__(self):
        return self.title

    def published_datasets(self):
        return self.datasets.filter(status="published")

    @property
    def frontend_url(self):
        return f"/article/{self.ident}"

    @property
    def frontend_absolute_url(self):
        return self._get_absolute_url(self.frontend_url)

    @property
    def frontend_preview_url(self):
        return self._get_absolute_url(f"/knowledge-base/preview/{self.id}")

    @property
    def is_knowledge_base(self):
        return bool(self.category.type == "knowledge_base")

    @property
    def is_news(self):
        return bool(self.category.type == "article")

    def tags_as_str(self, lang):
        return ", ".join(sorted([tag.name for tag in self.tags.filter(language=lang)], key=str.lower))

    @property
    def keywords_list(self):
        return [tag.to_dict for tag in self.tags.all()]

    @property
    def keywords(self):
        return self.tags

    @property
    def preview_link(self):
        return self.mark_safe(f'<a href="{self.frontend_preview_url}" class="btn" target="_blank">{_("Preview")}</a>')

    def migrate_news_to_cms(self):
        if not self.is_news:
            return
        news_index_model = apps.get_model("cms.NewsPageIndex")
        news_model = apps.get_model("cms.NewsPage")
        news_ct = ContentType.objects.get_for_model(news_model)
        news_index = news_index_model.objects.first()
        if not news_index:
            root_model = apps.get_model("cms.RootPage")
            news_index_ct = ContentType.objects.get_for_model(news_index_model)
            root = root_model.objects.first()
            if root:
                news_index = news_index_model(
                    title="Aktualności",
                    title_en="News",
                    content_type=news_index_ct,
                    show_in_menus=True,
                )
                root.add_child(instance=news_index)
        if not news_index.get_children().filter(title=self.title).exists():
            news = news_model(
                title=self.title,
                title_en=self.title_en or "",
                body=self.notes,
                body_en=self.notes_en or "",
                author=self.author or "",
                author_en=self.author or "",
                first_published_at=self.created,
                last_published_at=self.modified,
                views_count=self.views_count,
                content_type=news_ct,
                show_in_menus=True,
                live=bool(self.status == "published"),
            )
            news_index.add_child(instance=news)
            tags_pl = self.tags.filter(language="pl").values_list("name", flat=True)
            tags_en = self.tags.filter(language="en").values_list("name", flat=True)
            for tag in tags_pl:
                news.tags.add(tag)
            for tag in tags_en:
                news.tags_en.add(tag)
            if tags_pl or tags_en:
                news.save()

    i18n = TranslationField(fields=("title", "notes"))
    tracker = FieldTracker()
    slugify_field = "title"

    objects = SoftDeletableManager()
    trash = TrashManager()

    class Meta:
        verbose_name = _("Article")
        verbose_name_plural = _("Articles")
        db_table = "article"
        default_manager_name = "objects"
        indexes = [
            GinIndex(fields=["i18n"]),
        ]


class ArticleTrash(Article, metaclass=TrashModelBase):
    class Meta:
        proxy = True
        verbose_name = _("Trash")
        verbose_name_plural = _("Trash")

backend_latest/mcod/cms/models/landingpage.py
from hypereditor.fields import HyperFieldPanel
from wagtail.admin.edit_handlers import FieldPanel, MultiFieldPanel, PublishingPanel
from wagtail.api import APIField

from mcod.cms.api.fields import HyperEditorJSONField, LocalizedHyperField
from mcod.cms.models.base import BasePage


class LandingPageIndex(BasePage):
    parent_page_types = ["cms.RootPage"]
    subpage_types = ["cms.LandingPage"]

    max_count = 1
    fixed_slug = "promotion"
    fixed_url_path = "promotion/"

    class Meta:
        verbose_name = "Lista stron startowych"
        verbose_name_plural = "Listy stron startowych"


class LandingPage(BasePage):
    body = LocalizedHyperField(default=None)
    body_en = LocalizedHyperField(default=None, blank=True, null=True)

    parent_page_types = [
        "cms.LandingPageIndex",
    ]

    subpage_types = []

    i18n_fields = BasePage.i18n_fields + [
        "body",
    ]

    api_fields = BasePage.api_fields + [APIField("body", serializer=HyperEditorJSONField(source="body_i18n"))]

    content_panels_pl = BasePage.content_panels + [HyperFieldPanel("body")]

    content_panels_en = BasePage.content_panels_en + [HyperFieldPanel("body_en")]

    settings_panels = [
        PublishingPanel(),
        MultiFieldPanel(
            [
                FieldPanel("slug"),
                FieldPanel("show_in_menus"),
            ],
            "Ustawienia strony",
        ),
    ]

    class Meta:
        verbose_name = "Strona startowa"
        verbose_name_plural = "Strony startowe"

    def get_copyable_fields(self):
        return super().get_copyable_fields() + ["body"]

backend_latest/mcod/counters/models.py
from datetime import date

from django.db import models
from modeltrans.manager import MultilingualManager


class ResourceCounter(models.Model):

    resource = models.ForeignKey("resources.Resource", on_delete=models.CASCADE)
    timestamp = models.DateField(default=date.today)
    count = models.IntegerField(default=0)

    objects = MultilingualManager()

    class Meta:
        abstract = True


class ResourceViewCounter(ResourceCounter):
    pass


class ResourceDownloadCounter(ResourceCounter):
    pass

backend_latest/mcod/templates/wagtailvideos/videos/edit.html
{% extends "wagtailadmin/base.html" %}

{% load static wagtailadmin_tags i18n wagtailvideos_tags %}

{% block titletag %}{% blocktrans with title=video.title %}Editing video {{ title }}{% endblocktrans %}{% endblock %}

{% block extra_css %}
{{ block.super }}
<link rel="stylesheet" href="{% static 'wagtailvideos/css/edit-video.css' %}" type="text/css" /> {% endblock %}

{% block extra_js %}
{{ block.super }}
{% url 'wagtailadmin_tag_autocomplete' as autocomplete_url %}
<script>
    {{ form.media.css }}
    $(function() {
        $('#id_tags').tagit({
            autocomplete: {
                source: "{{ autocomplete_url|addslashes }}"
            }
        });
    });
</script>
{% endblock %}
{% block content %}
{% trans "Editing" as editing_str %}

{% include "wagtailadmin/shared/header.html" with title=editing_str subtitle=video.title icon="media" %}

<div class="row row-flush nice-padding">
    <div class="col6">
        <form action="{% url 'wagtailvideos:edit' video.id %}" method="POST" enctype="multipart/form-data" id="video-edit-form">
            {% csrf_token %}
            <ul class="fields">
                {% for field in form %}
                  {% if field.name == 'file' %}
                    {% include "wagtailvideos/videos/_file_field_as_li.html"  with li_classes="label-above label-uppercase" %}
                  {% elif field.is_hidden %}
                    {{ field }}
                  {% else %}
                    {% include "wagtailadmin/shared/field_as_li.html" with li_classes="label-above label-uppercase" %}
                  {% endif %}
                {% endfor %}
                <li>
                    <button type="submit" class="button button-longrunning" data-clicked-text="{% trans 'Saving...' %}">
                        <svg class="icon icon-spinner icon" aria-hidden="true" focusable="false"><use href="#icon-spinner"></use>
                        </svg>
                        <em>{% trans 'Save' %}</em>
                    </button>
                    {% if user_can_delete %}
                        <a href="{% url 'wagtailvideos:delete' video.id %}" class="button button-secondary no">{% trans "Delete video" %}</a>
                    {% endif %}
                </li>
            </ul>
        </form>
    </div>
    <div class="col6">
        <div class="row">
            <div class="col10 divider-after">
                {% video video controls style=max-width:100%;width:100%;height:auto; %}
            </div>
            <div class="col2">
                <dl style="margin-top: 0;">
                    {% if video.thumbnail %}
                    <dt>{% trans "Thumbnail" %}</dt>
                    <dd><img src="{{ video.thumbnail.url }}" alt="{% trans 'Video thumbnail' %}" /></dd>
                    {% endif %}
                    <dt>{% trans "Filesize" %}</dt>
                    <dd>{% if filesize %}{{ filesize|filesizeformat }}{% else %}{% trans "File not found" %}{% endif %}</dd>
                    {% if video.duration %}
                    <dt>{% trans "Duration" %}</dt>
                    <dd>{{ video.formatted_duration }}</dd>
                    {% endif %}
                    {% usage_count_enabled as uc_enabled %}
                    {% if uc_enabled %}
                        <dt>{% trans "Usage" %}</dt>
                        <dd>
                            <a href="{{ video.usage_url }}">{% blocktrans count usage_count=video.get_usage.count %}Used {{ usage_count }} time{% plural %}Used {{ usage_count }} times{% endblocktrans %}</a>
                        </dd>
                    {% endif %}
                </dl>
            </div>
        </div>
        <div class="row" style="margin-top: 2em;">
        {% if can_transcode %}
            <h2 class="u-text-transform-uppercase">{% trans "Transcodes" %}</h2>
            <p>{% trans "If you wish to generate HTML5 compliant transcodes use the form below. This may take a while depending on the length of the video." %}</p>
            {% if transcodes %}
            <h3 class="u-text-transform-uppercase">{% trans "Available Transcodes" %}</h3>
            <ul>
                {% for transcode in transcodes %}
                <li>
                    {% blocktrans with media_format=transcode.media_format quality=transcode.quality %}{{ media_format }} ({{ quality }} quality){% endblocktrans %}
                    {% if transcode.processing %}
                        <span class="processing">{% trans "(Processing... hold tight)" %} </span>
                    {% endif %}
                    {% if transcode.error_message %}
                        <span class="transcode-error">{% trans "ERROR:" %}</span>
                        <div class="transcode-error">
                            <pre> {{ transcode.error_message }}</pre>
                        </div>
                    {% endif %}
                </li>
                {% endfor %}
            </ul>
            {% endif %}
            <h3 class="u-text-transform-uppercase">{% trans "Create transcode" %}</h3>
            <form action="{% url 'wagtailvideos:create_transcode' video.id %}" method="POST">
                <ul class="fields">
                    {% csrf_token %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=transcode_form.media_format li_classes="label-above label-uppercase" %}
                    {% include "wagtailadmin/shared/field_as_li.html" with field=transcode_form.quality li_classes="label-above label-uppercase" %}
                    <li>
                        <input class="button" type="submit" value="{% trans 'Start' %}" />
                    </li>
                </ul>
            </form>
        {% else %}
            <br/><br/>
            <span class="transcode-error">{% trans "Ffmpeg is not found on your server or you have disabled transcodes. Please install Ffmepg and make sure that transcoding is enabled if you wish to transcode videos into an HTML5 video compliant format." %}</span>
        {% endif %}
        {% if tracks_action_url %}
            <h2 class="u-text-transform-uppercase">{% trans "Tracks" %}</h2>
            <p>{% trans 'You can add/edit subtitles or accessibility captions for this video. For information about the filetype that should be used see the mozilla docs on <a href="https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API">WebVTT</a>' %}</p>
                {% if video.track_listing %}
                <ul>
                {% for track in video.track_listing.tracks.all %}
                    <li>{{ track }}</li>
                {% endfor %}
                </ul>
                <a class="button" href="{{ tracks_action_url }}">{% trans "Edit" %}</a>
                {% else %}
                <a class="button" href="{{ tracks_action_url }}">{% trans "Add tracks" %}</a>
                {% endif %}
        {% endif %}
        </div>
    </div>
</div>
{% endblock %}